### ISSUE TITLE
Please use an OSI approved license

### ISSUE THREAD

**Issue by marcmerlin** [padolsey/sonic.js#11]
Hi,
I just had to delete your code from our source trees after I found it with a scan for bad licenses.

sonic.js is licensed WTFPL, which is not a proper license
https://en.wikipedia.org/w/index.php?title=WTFPL&oldid=712745928#Characteristics
https://en.wikipedia.org/w/index.php?title=WTFPL&oldid=712745928#Effectiveness_as_license_or_waiver
and then you have a top level license that is unlicense, contradicting the file header license.
Sadly, unlicense is not a proper license either.
http://programmers.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense

If you care to share you software without causing issues or worries for others, please use MIT/BSD, or some license like Apache2. Thanks.

**Comment by padolsey** [comment]
Apologies. I really wish I could just put code out there and not have to worry about this stuff. I guess I want the legal version of walking in the park and dropping a paper recipe on the ground, later to be found by individuals who've no idea I exist. I'm not a fan of copyright or attribution but in an attempt to reconcile I'm gonna look into MIT. I expect there'll be further headaches regarding retroactively changing license and what it means, legally, in regard to previous contributions via PRs.

This is so so silly.

**Comment by marcmerlin** [comment]
Sorry, I realize this is not fun, and not what you'd rather spend your time on.
Sadly, licensing is important if you care to have your code used by companies and/or entities that can be sued. 
On the plus side, you don't have to be a lawyer or re-invent the wheel, OSI has already categorized all the approved licenses for you, and the cliffs note is that MIT or BSD are indeed the simplest approved licenses that have the fewest restrictions 
WTFPL and Unlicense are sadly both a distraction that have caused a lot of wasted time on the internet, yours and mine :(

**Comment by marcmerlin** [comment]
thanks for taking care of it, I appreciate it.
