### ISSUE TITLE
HTML5 shims question

### ISSUE THREAD

**Issue by thednp** [padolsey/sonic.js#9]
I am curious to know if we use HTML5 shims, would these work with IE9 and below?
If yes, please reply as soon as you can. 

Thank you

(currently my laptop is under construction and cannot check it myself)

**Comment by padolsey** [comment]
It might work, I've not tested. Even with that, it still might be good to have a CSS or GIF fallback (by which point one may as well just not bother using Canvas in production).

Probably worth checking on http://modern.ie or http://browserstack.com

**Comment by thednp** [comment]
I checked your stuff with IE8, (back then I couldn't), and it doesn't work. 
Perhaps worth the effort of making some small adjustment and a polyfill. Just to have it cover all major browsers. (See my projects, perhaps you get some inspiration ;)

**Comment by padolsey** [comment]
Have you tried [excanvas](https://code.google.com/p/explorercanvas/)? For now I don't think it's worth building in any polyfills/shims, as that just adds bloat to the lib -- this kind of stuff can easily be added at the discretion of developers using sonic.js.
